// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3RQjo2jvB27_yYImgV4QV7-q2gLiJGeQ',
    appId: '1:593847008117:web:846c94e308921cc88cf13c',
    messagingSenderId: '593847008117',
    projectId: 'redditclone-linux',
    authDomain: 'redditclone-linux.firebaseapp.com',
    storageBucket: 'redditclone-linux.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Qj1n4rciIcUi6E5N1AJCOMRiQ72OV2o',
    appId: '1:593847008117:android:1f7076cfbc405d9c8cf13c',
    messagingSenderId: '593847008117',
    projectId: 'redditclone-linux',
    storageBucket: 'redditclone-linux.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGCFtynmXLCGo_LTkydE86mk33UzpIp8o',
    appId: '1:593847008117:ios:379d74a793037fc88cf13c',
    messagingSenderId: '593847008117',
    projectId: 'redditclone-linux',
    storageBucket: 'redditclone-linux.appspot.com',
    iosBundleId: 'com.example.redditcloneLinux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGCFtynmXLCGo_LTkydE86mk33UzpIp8o',
    appId: '1:593847008117:ios:00cbbcede75a328c8cf13c',
    messagingSenderId: '593847008117',
    projectId: 'redditclone-linux',
    storageBucket: 'redditclone-linux.appspot.com',
    iosBundleId: 'com.example.redditcloneLinux.RunnerTests',
  );
}
